targets:
  $default:
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/app/models/**

        options:
          explicit_to_json: true
          include_if_null: false

      # injectable_generator|injectable_builder:
      #   enabled: true
      #   generate_for:
      #     include:
      #       - lib/app/networking/**
      #       - lib/app/di/**
      #       - lib/app/utilities/**